### ISSUE TITLE
两个术语的翻译问题

### ISSUE THREAD

**Issue by wizardforcel** [straightdave/programming-elixir#10]
Comprehension => 推导式

Sigil => 符文

**Comment by straightdave** [comment]
感谢你的反馈。关于这两个单词的翻译，在文中都有说明。一般来说，我也不确定翻译是否贴切，但是请不要过于纠结具体翻译的词汇，重点是明白它说的是什么，对吧。
国内一些python书籍（或是一些高数书籍）把comprehension这个概念翻译成推导式、递推式；看过一个台湾那边的作者称之为速购。我觉得速购（快速构造集合）简短贴切，于是在这里使用。
关于sigil，早期程序书籍中也有这个概念，如basic语言，javascript等；而现代一些语言（如ruby）它将其作为语法糖的一个要素用得较多。而这些sigil作为语法糖也带来一些炫丽充满魔法感觉的作用，因此这里使用“魔法印”。见仁见智啦。
