### ISSUE TITLE
Can you support English version?

### ISSUE THREAD

**Issue by vanloc0301** [straightdave/programming-elixir#8]
I think many developers in the world can't read your repository. Language is the main problem.
I was using Google Translate but I can't understand many case in your repository.

This will pretty if you add English version to your repo?
Thank you very much.

**Comment by wuming123057** [comment]
http://elixir-lang.org/getting-started/introduction.html 
https://elixirschool.com
You can see these.

**Comment by Cifer-Y** [comment]
@vanloc0301 Hey bro, this repo is just the Chinese translation version of [elixir-lang official getting start](http://elixir-lang.org/getting-started/introduction.html)

**Comment by wuming123057** [comment]
You can look [Elixir School](https://elixirschool.com/) also.

**Comment by vanloc0301** [comment]
@Cifer-Y  - @wuming123057 : Thanks pro.
